-- Editor Values
STATE = 2
NAMEGIVING = 3
NAMETARGET = 4
EDITORDELAY = 8
LAYER = 9
EDITORDIR = 10
SCROLLAREA = 11
SCROLLAMOUNT = 12
EDITTARGET = 13
E_INEDITOR = 15
NAMEFLAG = 16
PATHSTYLE = 17
LEVELTYPE = 18
UNLOCKCOUNT = 19
TARGETSPRITE = 20
COLOURSETUPTYPE = 21
OBJECTSETUPTYPE = 22
PATHGATE = 23
PATHREQUIREMENT = 24
EDITORGRIDTYPE = 25
EDITORGRIDDELAY = 26

-- Editor Strings
NAMETOGIVE = 1
E_WORLD = 2
MENU = 3
LEVELFILE = 4
THEME = 5
PATHOBJECT = 6
CHANGEDOBJECTS = 7

-- Editor2 Values
MENU_XPOS = 2
MENU_YPOS = 3
MENU_XDIM = 4
MENU_YDIM = 5
CURSORSEXIST = 10
OBJECTWORDSWAP = 11
OBJLISTTYPE = 12
DOPAIRS = 13
EDITORTOOL = 14
TOOLUSED = 15
TOOL_X = 16
TOOL_Y = 17
ADVANCEDWORDS = 18
EXTENDEDMODE = 19
ALLOWSCROLL = 20
SORTING = 21
SORTING_TYPES = 22

MENU_XOFFSET = 25
MENU_YOFFSET = 26

-- Editor2 Strings
CUSTOMPARENT = 1
CUSTOMPARENTNAME = 2
MENUOPTION = 3
SEARCHSTRING = 4
AUTHOR = 5
SUBTITLE = 6
LEVELMUSIC = 7
LEVELPARTICLES = 8
WORLDAUTHOR = 9
ERRORCODE = 10

-- Editor3 Values
OBJECTDRAGGED = 1
RELOCATEDOBJECT = 2
DELETING = 3
PAGE = 4
LEVEL_OR_WORLD = 5
TOOLTIPTARGET = 6
TOOLTIPCHECK = 7
SHOWTOOLTIP = 8
DIFFICULTYNUM = 9
PREVLAYER = 10
UPLOADDONE = 11
UPLOADSUCCESS = 12
NOTHEMECONFIRM = 13
OBJCOLOURSWAP = 14
TEMP = 15
UNSAVED = 16
FULLSPRITELIST = 17
MAXPAGE = 18
EDITORDRAWING = 19
SUPEROLDLEVEL = 20
CURROBJX = 21
CURROBJY = 22
CURROBJTARGET = 23
CURROBJMENUTYPE = 24
DELAYEDSAVE = 25

-- Editor3 Strings
THEMENAME = 1
UPLOADLEVELID = 2
WORLDTOERASE = 3
PAGEMENU = 4
ESCBUTTON = 5
MENUEXTRA = 6
CURROBJNAME = 7
TEXTFILTERS = 8
PREVLEVELFILE = 9
GETMENUTYPE = 10

-- Editor4 Values
QUICKBAR_ID = 1

EDITOR_DISABLETIPS = 11
EDITOR_DISABLESLIDE = 17

SELECTIONX = 18
SELECTIONY = 19
SELECTIONWIDTH = 20
SELECTIONHEIGHT = 21
SELECTION_ON = 22
EDITOR_TUTORIAL = 23

-- Editor4 Strings
EDITOR_CURROBJTARGET = 3
TUTORIAL = 4
TUTORIALSLIDE = 5
SEARCHSTRING_CURROBJLIST = 6
TUTORIAL_EXTRA = 7
CURRENTTAGS = 8
CURRMENUITEM = 9

-- Button Values
BUTTON_DISABLED = 13
BUTTON_TIMER = 14
BUTTON_PRESSED = 15
BUTTON_SELECTED = 17
BUTTON_STOREDX = 18
BUTTON_STOREDY = 19

-- Button Strings
BUTTONFUNC = 1
BUTTONID = 2
BUTTONNAME = 3
BUTTONTEXT = 5
BUTTONTOOLTIP = 6

-- Button Flags
BUTTON_M_HOVERCLICK = 7
BUTTON_M_HOVERCLICK_CHECK = 8
BUTTON_SIDEBAR = 10

BUTTON_NOCHECKMARK = 18
BUTTON_USECUSTOMFONT = 19
BUTTON_SLIDING = 20

-- UI Element Values
OWNER = 1
YORIGIN = 16

-- UI Element Strings
OWNERMENU = 1
GROUP = 2
UI_CUSTOMCOLOUR = 4

-- UI Element Flags
NOSCROLL = 9

-- Unit Grid Unit Values
GRID_X = 19
GRID_Y = 20
GRID_TILE = 10

-- Editor_levelnum Flags
SPECIAL = 1

-- Editor_levelnum Values
LEVELNUMBER = 2
LEVELSTYLE = 3

-- Slider Values
SLIDER_CURR = 6
SLIDER_MIN = 7
SLIDER_MAX = 8

-- Slider Knob Values
SLIDERKNOB_OWNER = 2

-- Editor_levelplacer Values
ACTUALX = 6
ACTUALY = 7

OBJECTID = 2

-- Editor_tileplacer Values

SELECTION_XOFFSET = 18
SELECTION_YOFFSET = 19

-- Editor_preview_icon Values
ICONDIR = 6
ICONROOT = 8

-- Palette Values
PALETTE_WIDTH = 1
PALETTE_HEIGHT = 2

-- Hotbar button Values
HOTBAR_ID = 2

-- Icon Values
ICON_INLEVEL = 7

-- Levelpack completion icon values
ICON_DIRECTION = 1
ICON_FRAME = 2